# this file creates an object that writes CSVs generated by the DMM_monitor.py script to an sql database.
# It uses the configuration YAML file to find the file path for CSVs in the log directory for writing 
# to the database. The table is created if it doesn't exist, and the data is inserted with three columns:
# timestamp, time (s), and voltage (V). The database is named in the config file. 

import os
import sqlite3
import csv
import yaml

class SQLWriter:
    def __init__(self, config_file="config.yaml"):
        # Load configuration from YAML file
        with open(config_file, "r") as f:
            self.config = yaml.safe_load(f)

        self.db_name = self.config.get("database_name")

        # Connect to the SQLite database (or create it if it doesn't exist)
        self.conn = sqlite3.connect(self.db_name)
        self.cursor = self.conn.cursor()

        # Create the table if it doesn't exist
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS dmm_readings (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT,
                time REAL,
                voltage REAL
            )
        ''')
        self.conn.commit()

    def write_csv_to_db(self, csv_file):
        with open(csv_file, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                timestamp = row['timestamp']
                time_sec = float(row['time (s)'])
                voltage = float(row['voltage (V)'])
                self.cursor.execute('''
                    INSERT INTO dmm_readings (timestamp, time, voltage)
                    VALUES (?, ?, ?)
                ''', (timestamp, time_sec, voltage))
            self.conn.commit()

    def close(self):
        self.conn.close()